# Generated by Django 6.0.3 on 2026-04-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lf_module'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lfclaim',
            name='unique_lf_claim',
        ),
        migrations.RenameIndex(
            model_name='lfitem',
            new_name='api_lfitem_item_ty_f6d828_idx',
            old_name='lf_item_type_status_idx',
        ),
        migrations.AlterField(
            model_name='lfcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lfclaim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lfitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lflog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lfnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='lfclaim',
            unique_together={('item', 'claimant')},
        ),
    ]
