# Generated by Django 5.2.13 on 2026-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mess_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='hostel',
            field=models.CharField(choices=[('hostel_1', 'Hostel 1'), ('hostel_2', 'Hostel 2'), ('hostel_3', 'Hostel 3'), ('hostel_4', 'Hostel 4'), ('hostel_5', 'Hostel 5'), ('hostel_6', 'Hostel 6'), ('hostel_7', 'Hostel 7'), ('hostel_8', 'Hostel 8'), ('hostel_9', 'Hostel 9'), ('hostel_10', 'Hostel 10'), ('hostel_11', 'Hostel 11'), ('hostel_12', 'Hostel 12'), ('hostel_13', 'Hostel 13'), ('hostel_14', 'Hostel 14'), ('hostel_15', 'Hostel 15'), ('hostel_16', 'Hostel 16'), ('hostel_17', 'Hostel 17'), ('hostel_18', 'Hostel 18'), ('hostel_19', 'Hostel 19'), ('hostel_21', 'Hostel 21'), ('tansa_house', 'Tansa House')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACKS', 'Snacks'), ('DINNER', 'Dinner')], max_length=10),
        ),
        migrations.AlterField(
            model_name='guestcouponpurchase',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACKS', 'Snacks'), ('DINNER', 'Dinner')], max_length=10),
        ),
        migrations.AlterField(
            model_name='messadminprofile',
            name='hostel',
            field=models.CharField(choices=[('hostel_1', 'Hostel 1'), ('hostel_2', 'Hostel 2'), ('hostel_3', 'Hostel 3'), ('hostel_4', 'Hostel 4'), ('hostel_5', 'Hostel 5'), ('hostel_6', 'Hostel 6'), ('hostel_7', 'Hostel 7'), ('hostel_8', 'Hostel 8'), ('hostel_9', 'Hostel 9'), ('hostel_10', 'Hostel 10'), ('hostel_11', 'Hostel 11'), ('hostel_12', 'Hostel 12'), ('hostel_13', 'Hostel 13'), ('hostel_14', 'Hostel 14'), ('hostel_15', 'Hostel 15'), ('hostel_16', 'Hostel 16'), ('hostel_17', 'Hostel 17'), ('hostel_18', 'Hostel 18'), ('hostel_19', 'Hostel 19'), ('hostel_21', 'Hostel 21'), ('tansa_house', 'Tansa House')], max_length=30),
        ),
        migrations.AlterField(
            model_name='messhostelsettings',
            name='hostel',
            field=models.CharField(choices=[('hostel_1', 'Hostel 1'), ('hostel_2', 'Hostel 2'), ('hostel_3', 'Hostel 3'), ('hostel_4', 'Hostel 4'), ('hostel_5', 'Hostel 5'), ('hostel_6', 'Hostel 6'), ('hostel_7', 'Hostel 7'), ('hostel_8', 'Hostel 8'), ('hostel_9', 'Hostel 9'), ('hostel_10', 'Hostel 10'), ('hostel_11', 'Hostel 11'), ('hostel_12', 'Hostel 12'), ('hostel_13', 'Hostel 13'), ('hostel_14', 'Hostel 14'), ('hostel_15', 'Hostel 15'), ('hostel_16', 'Hostel 16'), ('hostel_17', 'Hostel 17'), ('hostel_18', 'Hostel 18'), ('hostel_19', 'Hostel 19'), ('hostel_21', 'Hostel 21'), ('tansa_house', 'Tansa House')], max_length=30, unique=True),
        ),
    ]
