# Generated by Django 5.2.13 on 2026-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contacts_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='maps_query',
        ),
        migrations.AddField(
            model_name='department',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Direct Google Maps URL for this department', max_length=500),
        ),
    ]
