# Generated by Django 5.2.13 on 2026-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_maps_query_to_maps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorScheduleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Schedule Cache',
            },
        ),
    ]
