# Generated by Django 6.0.4 on 2026-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_keycloak_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
